[project]
name = "gia-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "psycopg2>=2.9.11",
    "pyqt6>=6.9.1",
    "sqlalchemy>=2.0.44",
]
